use solutions;
SET @test_driver = "DRIVER001";
SET @start_time = CURRENT_TIMESTAMP(3);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
CALL Query_B("SELECT * from Payment;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT * from Payment WHERE Surcharge < 2;", TRUE);
CALL Query_B("SELECT Trip_ID from Payment WHERE Duration > 1;", TRUE);
CALL Query_B("SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;", TRUE);
CALL Query_B("SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;", TRUE);
SET @end_time = CURRENT_TIMESTAMP(3);
SELECT TIMEDIFF(@end_time, @start_time) AS total_query_time_solution_B_precise;

