use baseline;
SET @test_driver = "DRIVER001";
SET @start_time = CURRENT_TIMESTAMP(3);
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SELECT * from Payment;
SELECT * from Payment WHERE Driver_ID = @test_driver;
SELECT * from Payment WHERE Surcharge < 2;
SELECT Trip_ID from Payment WHERE Duration > 1;
SELECT * FROM Payment INNER JOIN Drivers ON Payment.Driver_ID=Drivers.Driver_ID WHERE Payment.Driver_ID = @test_driver;
SELECT distinct(Driver_Name) From Drivers INNER JOIN Payment ON Drivers.Driver_ID = Payment.Driver_ID WHERE Payment.Total < 5;
SET @end_time = CURRENT_TIMESTAMP(3);
SELECT TIMEDIFF(@end_time, @start_time) AS total_query_Baseline;

