use baseline;
SET @test_driver = "DRIVER001";
SET @start_time = CURRENT_TIMESTAMP(3);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SELECT sum(Total) from Payment WHERE Driver_ID = @test_driver;
SELECT AVG(Duration) from Payment WHERE Basefare < 15;
SELECT Count(Distinct(Driver_ID)) from Payment WHERE Surcharge < 1;
SELECT Total/Duration AS revenue_per_hour from Payment WHERE Duration < 1;
SELECT AVG(Total/Duration) AS avg_revenue_per_hour from Payment WHERE Basefare < 20;
SELECT Driver_ID, sum(Total), sum(Duration) FROM Payment GROUP BY Driver_ID ORDER BY sum(Total);
SET @end_time = CURRENT_TIMESTAMP(3);
SELECT TIMEDIFF(@end_time, @start_time) AS total_query_Baseline_computational;

